<?php

declare(strict_types=1);

/** Extra EN↔DE pairs merged by bin/build_glossary_seed.php */

return [
    // Bundesländer
    ['en' => 'Baden-Württemberg', 'de' => 'Baden-Württemberg', 'category' => 'location'],
    ['en' => 'Bavaria', 'de' => 'Bayern', 'category' => 'location'],
    ['en' => 'Berlin', 'de' => 'Berlin', 'category' => 'location'],
    ['en' => 'Brandenburg', 'de' => 'Brandenburg', 'category' => 'location'],
    ['en' => 'Bremen', 'de' => 'Bremen', 'category' => 'location'],
    ['en' => 'Hamburg', 'de' => 'Hamburg', 'category' => 'location'],
    ['en' => 'Hesse', 'de' => 'Hessen', 'category' => 'location'],
    ['en' => 'Lower Saxony', 'de' => 'Niedersachsen', 'category' => 'location'],
    ['en' => 'Mecklenburg-Vorpommern', 'de' => 'Mecklenburg-Vorpommern', 'category' => 'location'],
    ['en' => 'North Rhine-Westphalia', 'de' => 'Nordrhein-Westfalen', 'category' => 'location'],
    ['en' => 'Rhineland-Palatinate', 'de' => 'Rheinland-Pfalz', 'category' => 'location'],
    ['en' => 'Saarland', 'de' => 'Saarland', 'category' => 'location'],
    ['en' => 'Saxony', 'de' => 'Sachsen', 'category' => 'location'],
    ['en' => 'Saxony-Anhalt', 'de' => 'Sachsen-Anhalt', 'category' => 'location'],
    ['en' => 'Schleswig-Holstein', 'de' => 'Schleswig-Holstein', 'category' => 'location'],
    ['en' => 'Thuringia', 'de' => 'Thüringen', 'category' => 'location'],

    // More cities
    ['en' => 'Tübingen, Germany', 'de' => 'Tübingen, Deutschland', 'category' => 'location'],
    ['en' => 'Konstanz, Germany', 'de' => 'Konstanz, Deutschland', 'category' => 'location'],
    ['en' => 'Passau, Germany', 'de' => 'Passau, Deutschland', 'category' => 'location'],
    ['en' => 'Bayreuth, Germany', 'de' => 'Bayreuth, Deutschland', 'category' => 'location'],
    ['en' => 'Würzburg, Germany', 'de' => 'Würzburg, Deutschland', 'category' => 'location'],
    ['en' => 'Fulda, Germany', 'de' => 'Fulda, Deutschland', 'category' => 'location'],
    ['en' => 'Kaiserslautern, Germany', 'de' => 'Kaiserslautern, Deutschland', 'category' => 'location'],
    ['en' => 'Trier, Germany', 'de' => 'Trier, Deutschland', 'category' => 'location'],
    ['en' => 'Siegen, Germany', 'de' => 'Siegen, Deutschland', 'category' => 'location'],
    ['en' => 'Paderborn, Germany', 'de' => 'Paderborn, Deutschland', 'category' => 'location'],
    ['en' => 'Gütersloh, Germany', 'de' => 'Gütersloh, Deutschland', 'category' => 'location'],
    ['en' => 'Reutlingen, Germany', 'de' => 'Reutlingen, Deutschland', 'category' => 'location'],
    ['en' => 'Jena, Germany', 'de' => 'Jena, Deutschland', 'category' => 'location'],
    ['en' => 'Cottbus, Germany', 'de' => 'Cottbus, Deutschland', 'category' => 'location'],
    ['en' => 'Oldenburg, Germany', 'de' => 'Oldenburg, Deutschland', 'category' => 'location'],
    ['en' => 'Osnabrück, Germany', 'de' => 'Osnabrück, Deutschland', 'category' => 'location'],
    ['en' => 'Heilbronn, Germany', 'de' => 'Heilbronn, Deutschland', 'category' => 'location'],
    ['en' => 'Pforzheim, Germany', 'de' => 'Pforzheim, Deutschland', 'category' => 'location'],
    ['en' => 'Gera, Germany', 'de' => 'Gera, Deutschland', 'category' => 'location'],
    ['en' => 'Salzgitter, Germany', 'de' => 'Salzgitter, Deutschland', 'category' => 'location'],
    ['en' => 'Hildesheim, Germany', 'de' => 'Hildesheim, Deutschland', 'category' => 'location'],
    ['en' => 'Ludwigshafen, Germany', 'de' => 'Ludwigshafen, Deutschland', 'category' => 'location'],
    ['en' => 'Leverkusen, Germany', 'de' => 'Leverkusen, Deutschland', 'category' => 'location'],
    ['en' => 'Neuss, Germany', 'de' => 'Neuss, Deutschland', 'category' => 'location'],
    ['en' => 'Potsdam, Germany', 'de' => 'Potsdam, Deutschland', 'category' => 'location'],
    ['en' => 'Offenbach, Germany', 'de' => 'Offenbach, Deutschland', 'category' => 'location'],
    ['en' => 'Remscheid, Germany', 'de' => 'Remscheid, Deutschland', 'category' => 'location'],
    ['en' => 'Moers, Germany', 'de' => 'Moers, Deutschland', 'category' => 'location'],
    ['en' => 'Solingen, Germany', 'de' => 'Solingen, Deutschland', 'category' => 'location'],
    ['en' => 'Herne, Germany', 'de' => 'Herne, Deutschland', 'category' => 'location'],
    ['en' => 'Krefeld, Germany', 'de' => 'Krefeld, Deutschland', 'category' => 'location'],
    ['en' => 'Oberhausen, Germany', 'de' => 'Oberhausen, Deutschland', 'category' => 'location'],
    ['en' => 'Hamm, Germany', 'de' => 'Hamm, Deutschland', 'category' => 'location'],
    ['en' => 'Mülheim, Germany', 'de' => 'Mülheim, Deutschland', 'category' => 'location'],
    ['en' => 'Göttingen, Germany', 'de' => 'Göttingen, Deutschland', 'category' => 'location'],

    // Job titles — general
    ['en' => 'Customer Service Representative', 'de' => 'Kundenberater', 'category' => 'job'],
    ['en' => 'Customer Support', 'de' => 'Kundensupport', 'category' => 'job'],
    ['en' => 'Sales Assistant', 'de' => 'Verkaufsassistent', 'category' => 'job'],
    ['en' => 'Retail Sales', 'de' => 'Einzelhandel', 'category' => 'job'],
    ['en' => 'Cashier', 'de' => 'Kassierer', 'category' => 'job'],
    ['en' => 'Warehouse Worker', 'de' => 'Lagerarbeiter', 'category' => 'job'],
    ['en' => 'Forklift Driver', 'de' => 'Gabelstaplerfahrer', 'category' => 'job'],
    ['en' => 'Production Worker', 'de' => 'Produktionsmitarbeiter', 'category' => 'job'],
    ['en' => 'Machine Operator', 'de' => 'Maschinenbediener', 'category' => 'job'],
    ['en' => 'Assembly Line Worker', 'de' => 'Fließbandarbeiter', 'category' => 'job'],
    ['en' => 'Cleaner', 'de' => 'Reinigungskraft', 'category' => 'job'],
    ['en' => 'Security Guard', 'de' => 'Sicherheitsmitarbeiter', 'category' => 'job'],
    ['en' => 'Driver', 'de' => 'Fahrer', 'category' => 'job'],
    ['en' => 'Delivery Driver', 'de' => 'Lieferfahrer', 'category' => 'job'],
    ['en' => 'Nurse', 'de' => 'Pflegefachkraft', 'category' => 'job'],
    ['en' => 'Care Assistant', 'de' => 'Pflegehelfer', 'category' => 'job'],
    ['en' => 'Medical Assistant', 'de' => 'Medizinische Fachangestellte', 'category' => 'job'],
    ['en' => 'Physiotherapist', 'de' => 'Physiotherapeut', 'category' => 'job'],
    ['en' => 'Accountant', 'de' => 'Buchhalter', 'category' => 'job'],
    ['en' => 'Financial Analyst', 'de' => 'Finanzanalyst', 'category' => 'job'],
    ['en' => 'HR Specialist', 'de' => 'HR-Spezialist', 'category' => 'job'],
    ['en' => 'Recruiter', 'de' => 'Recruiter', 'category' => 'job'],
    ['en' => 'Marketing Manager', 'de' => 'Marketingmanager', 'category' => 'job'],
    ['en' => 'Content Writer', 'de' => 'Content Writer', 'category' => 'job'],
    ['en' => 'Graphic Designer', 'de' => 'Grafikdesigner', 'category' => 'job'],
    ['en' => 'UX Designer', 'de' => 'UX-Designer', 'category' => 'job'],
    ['en' => 'UI Designer', 'de' => 'UI-Designer', 'category' => 'job'],
    ['en' => 'Product Manager', 'de' => 'Produktmanager', 'category' => 'job'],
    ['en' => 'Business Development', 'de' => 'Business Development', 'category' => 'job'],
    ['en' => 'Consultant', 'de' => 'Berater', 'category' => 'job'],
    ['en' => 'Administrator', 'de' => 'Administrator', 'category' => 'job'],
    ['en' => 'Office Assistant', 'de' => 'Büroassistent', 'category' => 'job'],
    ['en' => 'Receptionist', 'de' => 'Empfangsmitarbeiter', 'category' => 'job'],
    ['en' => 'Secretary', 'de' => 'Sekretär', 'category' => 'job'],
    ['en' => 'Translator', 'de' => 'Übersetzer', 'category' => 'job'],
    ['en' => 'Interpreter', 'de' => 'Dolmetscher', 'category' => 'job'],
    ['en' => 'Teacher', 'de' => 'Lehrer', 'category' => 'job'],
    ['en' => 'Research Assistant', 'de' => 'Wissenschaftliche Hilfskraft', 'category' => 'job'],
    ['en' => 'PhD Student', 'de' => 'Doktorand', 'category' => 'job'],
    ['en' => 'Laboratory Technician', 'de' => 'Laborant', 'category' => 'job'],
    ['en' => 'Chemist', 'de' => 'Chemiker', 'category' => 'job'],
    ['en' => 'Biologist', 'de' => 'Biologe', 'category' => 'job'],
    ['en' => 'Mechanical Engineer', 'de' => 'Maschinenbauingenieur', 'category' => 'job'],
    ['en' => 'Electrical Engineer', 'de' => 'Elektroingenieur', 'category' => 'job'],
    ['en' => 'Civil Engineer', 'de' => 'Bauingenieur', 'category' => 'job'],
    ['en' => 'Automotive Engineer', 'de' => 'Automobilingenieur', 'category' => 'job'],
    ['en' => 'Process Engineer', 'de' => 'Verfahrensingenieur', 'category' => 'job'],
    ['en' => 'Maintenance Technician', 'de' => 'Wartungstechniker', 'category' => 'job'],
    ['en' => 'Electrician', 'de' => 'Elektriker', 'category' => 'job'],
    ['en' => 'Plumber', 'de' => 'Klempner', 'category' => 'job'],
    ['en' => 'Carpenter', 'de' => 'Tischler', 'category' => 'job'],
    ['en' => 'Chef', 'de' => 'Koch', 'category' => 'job'],
    ['en' => 'Waiter', 'de' => 'Kellner', 'category' => 'job'],
    ['en' => 'Bartender', 'de' => 'Barkeeper', 'category' => 'job'],
    ['en' => 'Hotel Receptionist', 'de' => 'Hotelrezeptionist', 'category' => 'job'],

    // More QA / dev tools
    ['en' => 'Cypress', 'de' => 'Cypress', 'category' => 'qa'],
    ['en' => 'Playwright', 'de' => 'Playwright', 'category' => 'qa'],
    ['en' => 'TestNG', 'de' => 'TestNG', 'category' => 'qa'],
    ['en' => 'JUnit', 'de' => 'JUnit', 'category' => 'qa'],
    ['en' => 'Pytest', 'de' => 'Pytest', 'category' => 'qa'],
    ['en' => 'Robot Framework', 'de' => 'Robot Framework', 'category' => 'qa'],
    ['en' => 'Appium', 'de' => 'Appium', 'category' => 'qa'],
    ['en' => 'Cucumber', 'de' => 'Cucumber', 'category' => 'qa'],
    ['en' => 'Behave', 'de' => 'Behave', 'category' => 'qa'],
    ['en' => 'Katalon', 'de' => 'Katalon', 'category' => 'qa'],
    ['en' => 'TestRail', 'de' => 'TestRail', 'category' => 'qa'],
    ['en' => 'Azure DevOps', 'de' => 'Azure DevOps', 'category' => 'qa'],
    ['en' => 'GitHub Actions', 'de' => 'GitHub Actions', 'category' => 'qa'],
    ['en' => 'GitLab CI', 'de' => 'GitLab CI', 'category' => 'qa'],
    ['en' => 'Jenkins', 'de' => 'Jenkins', 'category' => 'qa'],
    ['en' => 'Docker', 'de' => 'Docker', 'category' => 'qa'],
    ['en' => 'Kubernetes', 'de' => 'Kubernetes', 'category' => 'qa'],
    ['en' => 'AWS', 'de' => 'AWS', 'category' => 'qa'],
    ['en' => 'Azure', 'de' => 'Azure', 'category' => 'qa'],
    ['en' => 'Google Cloud', 'de' => 'Google Cloud', 'category' => 'qa'],
    ['en' => 'TypeScript', 'de' => 'TypeScript', 'category' => 'qa'],
    ['en' => 'React', 'de' => 'React', 'category' => 'qa'],
    ['en' => 'Vue.js', 'de' => 'Vue.js', 'category' => 'qa'],
    ['en' => 'Angular', 'de' => 'Angular', 'category' => 'qa'],
    ['en' => 'Node.js', 'de' => 'Node.js', 'category' => 'qa'],
    ['en' => 'Laravel', 'de' => 'Laravel', 'category' => 'qa'],
    ['en' => 'Symfony', 'de' => 'Symfony', 'category' => 'qa'],
    ['en' => 'Spring Boot', 'de' => 'Spring Boot', 'category' => 'qa'],
    ['en' => 'C#', 'de' => 'C#', 'category' => 'qa'],
    ['en' => 'C++', 'de' => 'C++', 'category' => 'qa'],
    ['en' => 'Go', 'de' => 'Go', 'category' => 'qa'],
    ['en' => 'Rust', 'de' => 'Rust', 'category' => 'qa'],
    ['en' => 'Ruby', 'de' => 'Ruby', 'category' => 'qa'],
    ['en' => 'Swift', 'de' => 'Swift', 'category' => 'qa'],
    ['en' => 'Kotlin', 'de' => 'Kotlin', 'category' => 'qa'],
    ['en' => 'Flutter', 'de' => 'Flutter', 'category' => 'qa'],
    ['en' => 'React Native', 'de' => 'React Native', 'category' => 'qa'],
    ['en' => 'MongoDB', 'de' => 'MongoDB', 'category' => 'qa'],
    ['en' => 'PostgreSQL', 'de' => 'PostgreSQL', 'category' => 'qa'],
    ['en' => 'Redis', 'de' => 'Redis', 'category' => 'qa'],
    ['en' => 'Elasticsearch', 'de' => 'Elasticsearch', 'category' => 'qa'],
    ['en' => 'Kafka', 'de' => 'Kafka', 'category' => 'qa'],
    ['en' => 'RabbitMQ', 'de' => 'RabbitMQ', 'category' => 'qa'],
    ['en' => 'GraphQL', 'de' => 'GraphQL', 'category' => 'qa'],
    ['en' => 'Microservices', 'de' => 'Microservices', 'category' => 'qa'],
    ['en' => 'CI/CD', 'de' => 'CI/CD', 'category' => 'qa'],
    ['en' => 'TDD', 'de' => 'TDD', 'category' => 'qa'],
    ['en' => 'BDD', 'de' => 'BDD', 'category' => 'qa'],
    ['en' => 'Kanban', 'de' => 'Kanban', 'category' => 'qa'],
    ['en' => 'Waterfall', 'de' => 'Wasserfallmodell', 'category' => 'qa'],
    ['en' => 'Code Review', 'de' => 'Code-Review', 'category' => 'qa'],
    ['en' => 'Pull Request', 'de' => 'Pull Request', 'category' => 'qa'],
    ['en' => 'Merge Request', 'de' => 'Merge Request', 'category' => 'qa'],
    ['en' => 'Technical Documentation', 'de' => 'Technische Dokumentation', 'category' => 'qa'],
    ['en' => 'User Stories', 'de' => 'User Stories', 'category' => 'qa'],
    ['en' => 'Acceptance Criteria', 'de' => 'Akzeptanzkriterien', 'category' => 'qa'],
    ['en' => 'Test Strategy', 'de' => 'Teststrategie', 'category' => 'qa'],
    ['en' => 'Test Report', 'de' => 'Testbericht', 'category' => 'qa'],
    ['en' => 'Bug Report', 'de' => 'Fehlerbericht', 'category' => 'qa'],
    ['en' => 'Severity', 'de' => 'Schweregrad', 'category' => 'qa'],
    ['en' => 'Priority', 'de' => 'Priorität', 'category' => 'qa'],
    ['en' => 'Reproduction Steps', 'de' => 'Schritte zur Reproduktion', 'category' => 'qa'],
    ['en' => 'Expected Result', 'de' => 'Erwartetes Ergebnis', 'category' => 'qa'],
    ['en' => 'Actual Result', 'de' => 'Tatsächliches Ergebnis', 'category' => 'qa'],
    ['en' => 'Environment', 'de' => 'Umgebung', 'category' => 'qa'],
    ['en' => 'Staging', 'de' => 'Staging', 'category' => 'qa'],
    ['en' => 'Production Environment', 'de' => 'Produktionsumgebung', 'category' => 'qa'],
    ['en' => 'Hotfix', 'de' => 'Hotfix', 'category' => 'qa'],
    ['en' => 'Release Notes', 'de' => 'Release Notes', 'category' => 'qa'],

    // Education extended
    ['en' => 'High School Diploma', 'de' => 'Abitur', 'category' => 'education'],
    ['en' => 'Vocational Training', 'de' => 'Berufsausbildung', 'category' => 'education'],
    ['en' => 'Apprenticeship', 'de' => 'Ausbildung', 'category' => 'education'],
    ['en' => 'Dual Study Program', 'de' => 'Duales Studium', 'category' => 'education'],
    ['en' => 'Exchange Semester', 'de' => 'Auslandssemester', 'category' => 'education'],
    ['en' => 'Erasmus', 'de' => 'Erasmus', 'category' => 'education'],
    ['en' => 'Information Technology', 'de' => 'Informationstechnologie', 'category' => 'education'],
    ['en' => 'Software Engineering', 'de' => 'Softwaretechnik', 'category' => 'education'],
    ['en' => 'Business Administration', 'de' => 'Betriebswirtschaft', 'category' => 'education'],
    ['en' => 'Mechanical Engineering', 'de' => 'Maschinenbau', 'category' => 'education'],
    ['en' => 'Electrical Engineering', 'de' => 'Elektrotechnik', 'category' => 'education'],
    ['en' => 'Industrial Engineering', 'de' => 'Wirtschaftsingenieurwesen', 'category' => 'education'],
    ['en' => 'Data Science', 'de' => 'Data Science', 'category' => 'education'],
    ['en' => 'Artificial Intelligence', 'de' => 'Künstliche Intelligenz', 'category' => 'education'],
    ['en' => 'Machine Learning', 'de' => 'Maschinelles Lernen', 'category' => 'education'],
    ['en' => 'Cybersecurity', 'de' => 'Cybersicherheit', 'category' => 'education'],
    ['en' => 'Grade Point Average', 'de' => 'Notendurchschnitt', 'category' => 'education'],
    ['en' => 'Honors', 'de' => 'Mit Auszeichnung', 'category' => 'education'],
    ['en' => 'Dean\'s List', 'de' => 'Dean\'s List', 'category' => 'education'],
    ['en' => 'Scholarship', 'de' => 'Stipendium', 'category' => 'education'],
    ['en' => 'Semester', 'de' => 'Semester', 'category' => 'education'],
    ['en' => 'Credit Points', 'de' => 'Leistungspunkte', 'category' => 'education'],
    ['en' => 'ECTS', 'de' => 'ECTS', 'category' => 'education'],

    // Soft skills
    ['en' => 'Time Management', 'de' => 'Zeitmanagement', 'category' => 'skills'],
    ['en' => 'Leadership', 'de' => 'Führung', 'category' => 'skills'],
    ['en' => 'Critical Thinking', 'de' => 'Kritisches Denken', 'category' => 'skills'],
    ['en' => 'Adaptability', 'de' => 'Anpassungsfähigkeit', 'category' => 'skills'],
    ['en' => 'Creativity', 'de' => 'Kreativität', 'category' => 'skills'],
    ['en' => 'Negotiation', 'de' => 'Verhandlung', 'category' => 'skills'],
    ['en' => 'Presentation Skills', 'de' => 'Präsentationsfähigkeiten', 'category' => 'skills'],
    ['en' => 'Conflict Resolution', 'de' => 'Konfliktlösung', 'category' => 'skills'],
    ['en' => 'Stakeholder Management', 'de' => 'Stakeholder-Management', 'category' => 'skills'],
    ['en' => 'Customer Focus', 'de' => 'Kundenorientierung', 'category' => 'skills'],
    ['en' => 'Results-oriented', 'de' => 'Ergebnisorientiert', 'category' => 'skills'],
    ['en' => 'Proactive', 'de' => 'Proaktiv', 'category' => 'skills'],
    ['en' => 'Reliable', 'de' => 'Zuverlässig', 'category' => 'skills'],
    ['en' => 'Flexible', 'de' => 'Flexibel', 'category' => 'skills'],
    ['en' => 'Organized', 'de' => 'Organisiert', 'category' => 'skills'],
    ['en' => 'Multitasking', 'de' => 'Multitasking', 'category' => 'skills'],
    ['en' => 'Intercultural Competence', 'de' => 'Interkulturelle Kompetenz', 'category' => 'skills'],
    ['en' => 'Work under pressure', 'de' => 'Arbeit unter Druck', 'category' => 'skills'],
    ['en' => 'Independent work', 'de' => 'Selbstständiges Arbeiten', 'category' => 'skills'],
    ['en' => 'Willingness to learn', 'de' => 'Lernbereitschaft', 'category' => 'skills'],

    // Common bullet starters (full patterns)
    ['en' => 'Tested customer service web and desktop applications through manual testing.', 'de' => 'Manuelles Testen von Kundenservice-Web- und Desktop-Anwendungen.', 'category' => 'bullet'],
    ['en' => 'Performed black box, exploratory, regression, smoke, and sanity testing.', 'de' => 'Durchführung von Black-Box-, explorativen, Regression-, Smoke- und Sanity-Tests.', 'category' => 'bullet'],
    ['en' => 'Designed, executed, and maintained detailed test cases and test scenarios.', 'de' => 'Erstellung, Ausführung und Pflege detaillierter Testfälle und Testszenarien.', 'category' => 'bullet'],
    ['en' => 'Identified, documented, and tracked software defects throughout the testing lifecycle.', 'de' => 'Identifizierung, Dokumentation und Nachverfolgung von Softwarefehlern im gesamten Testlebenszyklus.', 'category' => 'bullet'],
    ['en' => 'Collaborated with developers to reproduce, verify, and validate bug fixes.', 'de' => 'Zusammenarbeit mit Entwicklern zur Reproduktion, Verifizierung und Validierung von Fehlerbehebungen.', 'category' => 'bullet'],
    ['en' => 'Participated in sprint planning, QA reviews, and release validation.', 'de' => 'Teilnahme an Sprint-Planung, QA-Reviews und Release-Validierung.', 'category' => 'bullet'],
    ['en' => 'Performed cross-browser and cross-platform compatibility testing.', 'de' => 'Durchführung von browser- und plattformübergreifenden Kompatibilitätstests.', 'category' => 'bullet'],
    ['en' => 'Assisted in improving QA processes, testing standards, and documentation.', 'de' => 'Mitwirkung an der Verbesserung von QA-Prozessen, Teststandards und Dokumentation.', 'category' => 'bullet'],
    ['en' => 'Executed SQL queries for backend data validation and database testing.', 'de' => 'Ausführung von SQL-Abfragen zur Backend-Datenvalidierung und Datenbanktests.', 'category' => 'bullet'],
    ['en' => 'Logged and tracked defects through the defect life cycle using Mantis.', 'de' => 'Protokollierung und Nachverfolgung von Fehlern über den Fehlerlebenszyklus mit Mantis.', 'category' => 'bullet'],
    ['en' => 'Developed and maintained responsive websites using PHP, WordPress, HTML5, CSS3, JavaScript, and MySQL.', 'de' => 'Entwicklung und Pflege responsiver Websites mit PHP, WordPress, HTML5, CSS3, JavaScript und MySQL.', 'category' => 'bullet'],
    ['en' => 'Used Git for version control and collaborative development.', 'de' => 'Nutzung von Git für Versionskontrolle und kollaborative Entwicklung.', 'category' => 'bullet'],

    // Cover letter extended
    ['en' => 'Motivated professional', 'de' => 'Motivierte Fachkraft', 'category' => 'cover'],
    ['en' => 'Strong interest', 'de' => 'Großes Interesse', 'category' => 'cover'],
    ['en' => 'Relevant experience', 'de' => 'Relevante Erfahrung', 'category' => 'cover'],
    ['en' => 'Immediate availability', 'de' => 'Sofortige Verfügbarkeit', 'category' => 'cover'],
    ['en' => 'Work permit', 'de' => 'Arbeitserlaubnis', 'category' => 'cover'],
    ['en' => 'EU citizen', 'de' => 'EU-Bürger', 'category' => 'cover'],
    ['en' => 'Blue Card', 'de' => 'Blaue Karte', 'category' => 'cover'],
    ['en' => 'Relocation', 'de' => 'Umzug', 'category' => 'cover'],
    ['en' => 'Willing to relocate', 'de' => 'Umzugsbereit', 'category' => 'cover'],
    ['en' => 'On-site', 'de' => 'Vor Ort', 'category' => 'cover'],
    ['en' => 'Onboarding', 'de' => 'Onboarding', 'category' => 'cover'],
    ['en' => 'Probation period', 'de' => 'Probezeit', 'category' => 'cover'],
    ['en' => 'Annual salary', 'de' => 'Jahresgehalt', 'category' => 'cover'],
    ['en' => 'Gross salary', 'de' => 'Bruttogehalt', 'category' => 'cover'],
    ['en' => 'Collective agreement', 'de' => 'Tarifvertrag', 'category' => 'cover'],
    ['en' => 'Works council', 'de' => 'Betriebsrat', 'category' => 'cover'],
    ['en' => 'GmbH', 'de' => 'GmbH', 'category' => 'cover'],
    ['en' => 'AG', 'de' => 'AG', 'category' => 'cover'],
    ['en' => 'Startup', 'de' => 'Startup', 'category' => 'cover'],
    ['en' => 'Multinational company', 'de' => 'Internationales Unternehmen', 'category' => 'cover'],

    // Months
    ['en' => 'January', 'de' => 'Januar', 'category' => 'date'],
    ['en' => 'February', 'de' => 'Februar', 'category' => 'date'],
    ['en' => 'March', 'de' => 'März', 'category' => 'date'],
    ['en' => 'April', 'de' => 'April', 'category' => 'date'],
    ['en' => 'May', 'de' => 'Mai', 'category' => 'date'],
    ['en' => 'June', 'de' => 'Juni', 'category' => 'date'],
    ['en' => 'July', 'de' => 'Juli', 'category' => 'date'],
    ['en' => 'August', 'de' => 'August', 'category' => 'date'],
    ['en' => 'September', 'de' => 'September', 'category' => 'date'],
    ['en' => 'October', 'de' => 'Oktober', 'category' => 'date'],
    ['en' => 'November', 'de' => 'November', 'category' => 'date'],
    ['en' => 'December', 'de' => 'Dezember', 'category' => 'date'],
];
