services:
  libretranslate:
    container_name: ddev-${DDEV_SITENAME}-libretranslate
    image: libretranslate/libretranslate:latest
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    tty: true
    expose:
      - "5000"
    environment:
      - LT_HOST=0.0.0.0
      - LT_PORT=5000
      - LT_LOAD_ONLY=en,de
    volumes:
      - libretranslate-models:/home/libretranslate/.local

volumes:
  libretranslate-models: {}
